"""Export experiments_summary.csv to a LaTeX table file for inclusion.
Usage:
  python code/sim/export_table.py --csv code/sim/out/experiments_summary.csv --out MDPI_template_ACS/generated/ablation_table.tex
"""
import argparse
from pathlib import Path
import pandas as pd

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--csv', type=str, default='code/sim/out/experiments_summary.csv')
    ap.add_argument('--out', type=str, default='MDPI_template_ACS/generated/ablation_table.tex')
    args = ap.parse_args()

    df = pd.read_csv(args.csv)
    # Aggregate across seeds
    agg = df.groupby('scenario').agg(
        success_rate=('success','mean'),
        steps_to_goal=('steps_to_goal','mean'),
        violations=('violations','mean'),
        final_goal_dist=('final_goal_dist','mean'),
    ).reset_index()

    # Build LaTeX tabularx string
    lines = []
    lines.append('% Auto-generated by export_table.py')
    lines.append(r'\begin{table}[H]')
    lines.append(r'\caption{Ablation metrics aggregated over seeds. Higher success rate and lower steps/violations are better.}\label{tab:ablation}')
    lines.append(r'\begin{tabular}{lcccc}')
    lines.append(r'\toprule')
    lines.append(r'Scenario & Success Rate & Steps to Goal & Violations & Final Dist \\')
    lines.append(r'\midrule')
    def esc(name: str) -> str:
        return name.replace('_', r'\_')
    for _, r in agg.iterrows():
        scen = esc(r['scenario'])
        lines.append(f"{scen} & {r['success_rate']:.2f} & {r['steps_to_goal']:.1f} & {r['violations']:.1f} & {r['final_goal_dist']:.2f} " + r"\\")
    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\end{table}')

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f"[OK] Wrote LaTeX table: {out_path.resolve()}")

if __name__ == '__main__':
    main()
