"""Generate a LaTeX table enumerating scenario parameters.
Usage:
  python code/sim/export_scenario_table.py --out MDPI_template_ACS/generated/scenario_table.tex
"""
import argparse
from pathlib import Path
from scenarios import get_scenarios

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='MDPI_template_ACS/generated/scenario_table.tex')
    args = ap.parse_args()

    scenarios = get_scenarios()
    lines = []
    lines.append('% Auto-generated by export_scenario_table.py')
    lines.append(r'\begin{table}[H]')
    lines.append(r'\caption{Simulation scenario parameter grid. Latency $L$ (steps), dropout probability $p_d$, Gaussian noise standard deviation $\sigma$.}\label{tab:scenarios}')
    lines.append(r'\begin{tabular}{lccc}')
    lines.append(r'\toprule')
    lines.append(r'Scenario & $L$ & $p_d$ & $\sigma$ \\')
    lines.append(r'\midrule')
    def esc(name: str) -> str:
        """Escape LaTeX special chars minimally (currently underscores)."""
        return name.replace('_', r'\_')
    for sc in scenarios:
        name = esc(sc['name'])
        lines.append(f"{name} & {sc['latency_steps']} & {sc['dropout_prob']} & {sc['noise_std']} " + r"\\")
    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\end{table}')

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f"[OK] Wrote scenario table: {out_path.resolve()}")

if __name__ == '__main__':
    main()
